# Generated by Django 2.2 on 2020-06-21 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
        ('UserFiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='cod_user',
        ),
        migrations.AddField(
            model_name='files',
            name='cod_cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Cliente.Cliente'),
            preserve_default=False,
        ),
    ]
