# Generated by Django 2.2 on 2020-06-19 17:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20200617_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth_user',
            name='key_expires',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 6, 19, 17, 49, 51, 805294, tzinfo=utc), null=True),
        ),
    ]
