# Generated by Django 2.2 on 2020-06-21 03:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20200619_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth_user',
            name='key_expires',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 6, 21, 3, 13, 53, 403271, tzinfo=utc), null=True),
        ),
    ]
