# Generated by Django 2.2 on 2020-10-13 23:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20200621_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth_user',
            name='key_expires',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 10, 13, 23, 33, 34, 303650, tzinfo=utc), null=True),
        ),
    ]
