# Generated by Django 2.2 on 2020-10-13 23:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20201013_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth_user',
            name='fec_nacimiento',
        ),
        migrations.AddField(
            model_name='auth_user',
            name='ruc',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='auth_user',
            name='key_expires',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 10, 13, 23, 47, 44, 75624, tzinfo=utc), null=True),
        ),
    ]
