# Generated by Django 2.2 on 2020-10-14 03:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20201013_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth_user',
            name='ruc',
        ),
        migrations.AlterField(
            model_name='auth_user',
            name='key_expires',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 10, 14, 3, 26, 32, 987275, tzinfo=utc), null=True),
        ),
    ]
